# Generated by Django 3.2.4 on 2021-07-05 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_contactss_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactss',
            old_name='Address',
            new_name='message',
        ),
    ]
