# Generated by Django 3.2.4 on 2021-07-05 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terms_conditions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='term_cond',
            new_name='privacy_policy',
        ),
    ]
