# Generated by Django 3.2.4 on 2021-07-05 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terms_conditions', '0002_rename_term_cond_privacy_policy'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='privacy_policy',
            new_name='term_cond',
        ),
    ]
